"""updated post status

Revision ID: 5dd1d73018a0
Revises: 64a93320f509
Create Date: 2021-10-29 16:16:10.454482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd1d73018a0'
down_revision = '64a93320f509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'status')
    # ### end Alembic commands ###
