"""updated post and attachments

Revision ID: 64a93320f509
Revises: 147ac1a23544
Create Date: 2021-10-29 14:21:27.846977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64a93320f509'
down_revision = '147ac1a23544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('project_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('attachments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('attachments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'attachments', ['uuid'])
    op.drop_constraint('attachments_post_uuid_fkey', 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'projects', ['project_uuid'], ['uuid'])
    op.drop_column('attachments', 'post_uuid')
    op.add_column('post', sa.Column('upload_url', sa.String(), nullable=True))
    op.add_column('post', sa.Column('platform_id', sa.String(), nullable=True))
    op.add_column('post', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('post', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('post', sa.Column('project_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'post', ['uuid'])
    op.create_foreign_key(None, 'post', 'projects', ['project_uuid'], ['uuid'])
    op.create_unique_constraint(None, 'projects', ['uuid'])
    op.add_column('sm_audit', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('sm_audit', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('sm_audit', sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('sm_audit', sa.Column('post_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'sm_audit', ['uuid'])
    op.create_foreign_key(None, 'sm_audit', 'users', ['user_uuid'], ['uuid'])
    op.create_foreign_key(None, 'sm_audit', 'post', ['post_uuid'], ['uuid'])
    op.create_unique_constraint(None, 'socialmedia', ['uuid'])
    op.create_unique_constraint(None, 'uploads', ['uuid'])
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'uploads', type_='unique')
    op.drop_constraint(None, 'socialmedia', type_='unique')
    op.drop_constraint(None, 'sm_audit', type_='foreignkey')
    op.drop_constraint(None, 'sm_audit', type_='foreignkey')
    op.drop_constraint(None, 'sm_audit', type_='unique')
    op.drop_column('sm_audit', 'post_uuid')
    op.drop_column('sm_audit', 'user_uuid')
    op.drop_column('sm_audit', 'is_deleted')
    op.drop_column('sm_audit', 'is_active')
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'project_uuid')
    op.drop_column('post', 'is_deleted')
    op.drop_column('post', 'platform')
    op.drop_column('post', 'platform_id')
    op.drop_column('post', 'upload_url')
    op.add_column('attachments', sa.Column('post_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key('attachments_post_uuid_fkey', 'attachments', 'post', ['post_uuid'], ['uuid'])
    op.drop_constraint(None, 'attachments', type_='unique')
    op.drop_column('attachments', 'is_deleted')
    op.drop_column('attachments', 'is_active')
    op.drop_column('attachments', 'project_uuid')
    # ### end Alembic commands ###
